[theme]
base = "light"
primaryColor = "#ff77aa"
backgroundColor = "#fffdf2"
secondaryBackgroundColor = "#fff7fb"
textColor = "#333333"
font = "sans serif"

[theme.sidebar]
widgetBackgroundColor = "#F0F2F6"
widgetBorderColor = "#DCDFE4"
skeletonBackgroundColor = "#E1E4E8"

[server]
headless = true
